#!/bin/bash -e

wd=$(pwd)
source ./paths
source ./funcs

usage() {
    echo "
    -o,--outputdir: output directory for databases. default is /n/scratch3/users/a/ak586/microtrawler/0_databases
    -n,--nctc: output filename for NCTC db. default is nctc_db.csv
    -c,--cip: output filename for CIP db. default is cip_db.csv
    "
}

dl_nctc_seqs() {
    job=$OUTPUTDIR/DLSEQS-NCTC_microtrawler.job
    cp $jobt_1 $job
    sed -i "2i #SBATCH -o $OUTPUTDIR/JOBOUTPUT_dl-NCTC-seqs" $job
    #TODO
    echo "$scriptdir/generic/extract_dates $OUTPUTDIR/$NCTCNAME > $OUTPUTDIR/nctc_dates" >> $job
    echo "grep -v '\-1' $OUTPUTDIR/nctc_dates | tr -d ' ' > $OUTPUTDIR/nctc_dates_nonull" >> $job
    echo "cut -f1 $OUTPUTDIR/nctc_dates_nonull > $OUTPUTDIR/nctc_dates_nonull_onlystrain" >> $job
    #echo "grep -v '\-1' $OUTPUTDIR/nctc_dates | tr -d ' ' | awk '{if(\$2<=1940){print \$0}}' > $OUTPUTDIR/nctc_ancient_strains" >> $job
    #echo "cut -f1 $OUTPUTDIR/nctc_ancient_strains > $OUTPUTDIR/nctc_ancient_strains_nodate" >> $job
    echo $job
}

dl_cip_seqs() {
    job=$OUTPUTDIR/DLSEQS-CIP_microtrawler.job
    cp $jobt_1 $job
    sed -i "2i #SBATCH -o $OUTPUTDIR/JOBOUTPUT_dl-CIP-seqs" $job
    echo "$projectdir/cip_trawler -o $OUTPUTDIR/$CIPNAME --scriptdir $scriptdir" >> $job
    echo "$scriptdir/cip/extract_dates $OUTPUTDIR/$CIPNAME > $OUTPUTDIR/cip_dates" >> $job
    echo "grep -v '\-1' $OUTPUTDIR/cip_dates | tr -d ' ' | awk '{if(\$2<=1940){print \$0}}' > $OUTPUTDIR/cip_ancient_strains" >> $job
    echo "cut -f1 $OUTPUTDIR/cip_ancient_strains > $OUTPUTDIR/cip_ancient_strains_nodate" >> $job
    echo $job
}

main() {
    OUTPUTDIR="/n/scratch3/users/a/ak586/microtrawler/1_sequences"
    for i in "$@"; do
    case $i in
        -o|--outputdir)
        OUTPUTDIR="$2"
        shift
        shift
        ;;
        -n|--nctc)
        NCTCNAME="$2"
        shift
        shift
        ;;
        -c|--cip)
        CIPNAME="$2"
        shift
        shift
        ;;
        -h|--help)
        usage
        exit
        ;;
        *)
        ;;
    esac
    done

    mkdir -p $OUTPUTDIR
    nctc_job=$(dl_nctc_db)
    cip_job=$(dl_cip_db)
    echo ""$(sbatch $nctc_job | cut -d' '  -f4)":"$(sbatch $cip_job | cut -d' '  -f4)""
}
main "$@"
