#!/bin/bash -e

wd=$(pwd)
source ./paths
source ./funcs

usage() {
    echo "
    -i,--inputdir : input directory of output from step 1. default is /n/scratch3/users/a/ak586/microtrawler/1_sequences
    -o,--outputdir: base output directory for rgi. default is /n/scratch3/users/a/ak586/microtrawler/2_rgi
    -c,--commands: number of RGI commands to submit per job. default is 50
    "
}

find_unassembled_seqs() {
    rm -f $BASEOUTPUTDIR/unassembled_fastas 2> /dev/null
    for i in $(fd -a "assembly_21.fa" $INPUTDIR); do
        echo "$(basename $(dirname $(dirname $i)))" >> $BASEOUTPUTDIR/unassembled_fastas
    done
}

build_files() {
    rm -f $BASEOUTPUTDIR/output_dirs 2> /dev/null
    #fd "*.fa" -a $INPUTDIR --glob | grep -v -f $BASEOUTPUTDIR/unassembled_fastas | sort > $BASEOUTPUTDIR/input_fastas
    fd "*.fa" -a $INPUTDIR --glob | sort > $BASEOUTPUTDIR/input_fastas
    #for i in $(fd "*.fa" --base-directory $INPUTDIR --glob | grep -v -f $BASEOUTPUTDIR/unassembled_fastas | sort)
    for i in $(fd "*.fa" --base-directory $INPUTDIR --glob | sort)
    do 
        #x=$(basename "$(dirname $(dirname $i))")
        x=$(dirname $(dirname $i))
        y=$(basename $i .fa)
        echo "$BASEOUTPUTDIR/$x/$y" >> $BASEOUTPUTDIR/output_dirs
    done
}

create_jobs() {
    mapfile -t fasta_input_list < $BASEOUTPUTDIR/input_fastas
    mapfile -t output_dir_list < $BASEOUTPUTDIR/output_dirs
    mkdir -p $
    rm -r "$BASEOUTPUTDIR/jobs" 2> /dev/null
    mkdir -p "$BASEOUTPUTDIR/jobs/outputs"

    jobctr=0
    rgictr=0
    for i in "${!fasta_input_list[@]}"; do
        outdir="${output_dir_list[i]}"
        mkdir -p "$outdir"
        fasta="${fasta_input_list[i]}"
        fasta_fname="$(basename $fasta .fa)"
        output_basename="$outdir"/"$fasta_fname"_abr-search
        wget --output-document "$BASEOUTPUTDIR/rgi" https://card.mcmaster.ca/latest/data

        if [ -s "$output_basename".rgi_out.txt ]; then
            echo "Looks like $fasta has already been analyzed! Skipping."
        else
            echo "Adding $fasta to be analyzed"
            if [ $rgictr -eq 0 ] || [ $rgictr -eq $1 ]; then
                rgictr=1
                job="$BASEOUTPUTDIR/jobs/FINDRESISTANCE_$jobctr-microtrawler.job"
                cp $jobt_2 $job
                sed -i "2i #SBATCH -o $BASEOUTPUTDIR/jobs/outputs/JOBOUTPUT_$jobctr-find-resistance" $job
                echo "rgi load --card_json $BASEOUTPUTDIR/rgi" >> $job
                ((jobctr++)) || true
            fi
            echo "rgi main -i "$fasta" -o "$output_basename".rgi_out --exclude_nudge --clean --split_prodigal_jobs -n 12" >> $job
            echo ""$fasta" > $outdir/fasta_analyzed" >> $job
            echo "echo "Finished analyzing $fasta"" >> $job
            ((rgictr++)) || true
        fi
    done
}

submit_jobs() {
    joblist=""
    if [ -z $DEPENDENCY ]; then
        for j in $(fd -a "FINDRESISTANCE_*-microtrawler.job" --glob $BASEOUTPUTDIR); do
            jobid=$(sbatch $j | cut -d' ' -f4)
            joblist+="$jobid:"
        done
    else
        for j in $(fd -a "FINDRESISTANCE_*-microtrawler.job" --glob $BASEOUTPUTDIR); do
            jobid=$(sbatch --dependency=afterok:"$DEPENDENCY" $j | cut -d' ' -f4)
            joblist+="$jobid:"
        done
    fi
    echo $joblist
}

main() {
    INPUTDIR="/n/scratch3/users/a/ak586/microtrawler/1_sequences"
    BASEOUTPUTDIR="/n/scratch3/users/a/ak586/microtrawler/2_rgi"
    COMMANDS=50
    for i in "$@"; do
    case $i in
        -i|--inputdir)
        INPUTDIR="$2"
        shift
        shift
        ;;
        -o|--outputdir)
        BASEOUTPUTDIR="$2"
        shift
        shift
        ;;
        -c|--commands)
        COMMANDS="$2"
        shift
        shift
        ;;
        -d|--dependency)
        DEPENDENCY="$2"
        shift
        shift
        ;;
        -h|--help)
        usage
        exit
        ;;
        *)
        ;;
    esac
    done

    mkdir -p "$BASEOUTPUTDIR/jobs"
    #find_unassembled_seqs
    build_files
    create_jobs $COMMANDS
    submit_jobs
}
main "$@"
