#!/bin/bash

tooldir="/n/data1/hms/dbmi/baym/arya/tools"

projectdir="/n/data1/hms/dbmi/baym/arya/projects/MicroTrawler"
scriptdir="$projectdir/helper_scripts"

jobdir="/n/data1/hms/dbmi/baym/arya/job_templates"
jobt_0="$jobdir/microt_0.jobtemp"
