#!/bin/bash -e

wd=$(pwd)
source ./paths
source ./funcs

usage() {
    echo ""
}


main() {
    OUTPUTDIR="/n/scratch3/users/a/ak586/microtrawler"
    for i in "$@"; do
    case $i in
        -o|--outputdir)
        OUTPUTDIR="$2"
        shift
        shift
        ;;
        -s|--step)
        STEP="$2"
        shift
        shift
        ;;
        -h|--help)
        usage
        exit
        ;;
        *)
        ;;
    esac
    done
    
    mkdir -p $OUTPUTDIR
    newl
    log " " " " "Running Microtrawler pipeline"
    log "Analysis Directory" "$OUTPUTDIR"
    if [[ $STEP = "0" ]]; then
        log "Downloading up-to-date culture reference databases" "" "Step 0"
        dbjobnums=$(./0_dl-db -o "$OUTPUTDIR/0_databases")
        dbjobnums=${dbjobnums%?}
        log "Download database jobs submitted" "$dbjobnums"
        newl
    fi

    if [[ $STEP < "2" ]]; then
        log "Downloading assembled sequences for isolates" "" "Step 1"
        if [ ! -z $dbjobnums ]; then
            seqjobnums=$(./1_dl-seqs -i "$OUTPUTDIR/0_databases" -o "$OUTPUTDIR/1_sequences" --dependency $dbjobnums)
        else
            seqjobnums=$(./1_dl-seqs -i "$OUTPUTDIR/0_databases" -o "$OUTPUTDIR/1_sequences")
        fi
        seqjobnums=${seqjobnums%?}
        log "Download sequence jobs submitted" "$seqjobnums"
    fi

    if [[ $STEP < "3" ]]; then
        log "Searching for antibiotic resistance" "" "Step 2"
        if [ ! -z $seqjobnums ]; then
            rgijobnums=$(./2_analyze-seqs -i "$OUTPUTDIR/1_sequences" -o "$OUTPUTDIR/2_rgi" --dependency $seqjobnums -c 50)
        else
            rgijobnums=$(./2_analyze-seqs -i "$OUTPUTDIR/1_sequences" -o "$OUTPUTDIR/2_rgi" -c 50)
        fi
        rgijobnums=${rgijobnums%?}
        log "Antibiotic resistance jobs submitted" "$rgijobnums"
    fi
exit

    if [[ $STEP < "4" ]]; then
        log "Performing meta-analysis" "" "Step 3"
        ./3_analyze -i "$OUTPUTDIR/2_rgi" -o "$OUTPUTDIR/3_analysis" -d "$OUTPUTDIR/0_databases" -f "$OUTPUTDIR/1_sequences"
        #log "Analysis pipeline jobs submitted" "$analysisjobnums"
    fi
}

main "$@"
